name: "Lint PR"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Check Java version
    runs-on: ubuntu-latest
    steps:
      - name: Build with Maven
        run: java -version
