name: My workflow
on: 
  push:
    branches:
      - main

jobs:
  job:
    name: test-job
    runs-on: ubuntu-latest
    steps:
      - id: step-01
        run: echo "POD_NAME=a" >> $GITHUB_OUTPUT
      - id: step-02
        run: echo "POD_NAME=b" >> $GITHUB_OUTPUT
      - id: step-3
        env:
          STEP_01_RESULT: ${{ steps.step-01.outputs.POD_NAME }}
          STEP_02_RESULT: ${{ steps.step-02.outputs.POD_NAME }}
        run: |
          echo $STEP_01_RESULT
          echo $STEP_02_RESULT
