name: My workflow
on: 
  push:
    branches:
      - project/*
    tags:
      - "*.*.*"
      - "v*.*.*"
      - "dev-v*.*.*"

jobs:
  job:
    name: test-job
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/checkout
      - run: "echo hello"
