name: My workflow
on:
  pull_request:


env:
  PLATFORMS: "linux/amd64,linux/arm64"

jobs:
  job:
    name: test-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Git config
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:master
          platforms: ${{ env.PLATFORMS }}
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          platforms: ${{ env.PLATFORMS }}
          driver-opts: |
            image=moby/buildkit:master
            network=host
          buildkitd-flags: "--debug --oci-worker-gc=false"
      - name: docker run
        run: |
          ls /usr/bin

          which qemu-aarch64-static

          docker run --rm -v /usr/bin/qemu-aarch64-static:/usr/bin/qemu-aarch64-static vdaas/vald-agent-ngt:v1.7.10
      # - name: Setup Docker Buildx
      #   id: buildx
      #   uses: docker/setup-buildx-action@v3
      #   with:
      #     version: latest
      #     platforms: ${{ env.PLATFORMS }}
      #     driver-opts: |
      #       image=moby/buildkit:master
      #       network=host
      #     buildkitd-flags: "--debug --oci-worker-gc=false"
      # - name: Build
      #   run: |
      #     DOCKER_BUILDKIT=1 docker buildx build --platform ${PLATFORMS} --progress plain --builder ${BUILDER} -f ./dockers/Dockerfile .
      #   env:
      #     BUILDER: ${{ steps.buildx.outputs.name }}
