name: My workflow
on: 
  push:
    branches:
      - main

jobs:
  job:
    name: test-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: hoge
        uses: ./.github/actions/test
      - run: echo ${{ steps.hoge.outputs.POD_NAME }}
