name: My workflow
on: 
  push:
    branches:
      - main

jobs:
  job:
    name: test-job
    runs-on: ubuntu-latest
    steps:
      - id: hoge
        uses: ./.github/actions/test
      - run: echo ${{ steps.outputs.hoge.POD_NAME }}
