name: My workflow
on:
  pull_request:


env:
  PLATFORMS: "linux/amd64,linux/arm64"

jobs:
  job:
    name: test-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Git config
        run: |
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:master
          platforms: linux/amd64,linux/arm64
      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          platforms: linux/amd64,linux/arm64
          driver-opts: |
            image=moby/buildkit:master
            network=host
          buildkitd-flags: "--debug --oci-worker-gc=false"
      - name: Build
        run: |
          DOCKER_BUILDKIT=1 docker buildx build --platform ${PLATFORMS} --builder ${BUILDER} -f ./dockers/Dockerfile
          echo ${PLATFORMS}
        env:
          BUILDER: ${{ steps.buildx.outputs.name }}
