name: My workflow
on: 
  push:
    branches:
      - project/*
    tags:
      - "*.*.*"
      - "v*.*.*"
      - "dev-v*.*.*"

jobs:
  job:
    name: test-job
    runs-on: ubuntu-latest
    if: ${{ startsWith( github.ref, 'refs/tags/' ) && !startsWith( github.ref, 'refs/tags/dev' ) }}
    steps:
      - uses: actions/checkout@v3
      - run: "echo hello"
